# ==============================
# Aplicação
# ==============================
spring.application.name=agenda

# Ativa cores ANSI no console (erros em vermelho, etc.)
spring.output.ansi.enabled=always

# Remove stacktrace dos erros exibidos no navegador
spring.web.error.include-stacktrace=never

# ==============================
# Banco de Dados (PostgreSQL)
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_appointment
spring.datasource.username=postgres
spring.datasource.password=1234

# Encoding padrão para scripts SQL
spring.sql.init.encoding=UTF-8

# Garante que o JPA crie as tabelas antes de rodar o data.sql (No h2, aqui vamos usar o FlyWay)
# spring.jpa.defer-datasource-initialization=true

# Cria as Tabelas no Banco de Dados Postgre, mas sem versionamento! 
# spring.jpa.generate-ddl = true

# Criar SCRIPT de Migração create.sql (RODE APENAS uma vês por versão!!!)

# spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
# spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
# spring.jpa.properties.hibernate.hbm2ddl.delimiter=; 